version: "3"

services:
  mongo:
    image: mongo:3
    restart: always
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    restart: always
    image: clean-node-api
    command: npm run debug
    volumes:
      - ./dist:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
