version: "3"

services:
	mongo:
		image: mongo:3
		restart: always
		volumes:
			- ./data:/data/db
		ports:
			- "27017:27017"

	api:
		build: .
		restart: always
		image: clean-node-api
		command: npm start
		volumes:
			- ./dist:/usr/src/app/dist
		ports:
			- "5050:5050"
		links:
			- mongo
