version: "3"

services:
  mongo:
    container_name: clean-node-api
    image: mongo:3
    restart: always
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: mongo-clean-node-api
    image: node:12-alpine
    working_dir: /usr/src/app
    restart: always
    command: sh -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/app/dist/
      - ./package.json:/usr/src/app/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
